### ISSUE TITLE
Undefinied variable 'x_solv' in Ion.f90

### ISSUE THREAD

**Issue by gcapes** [UoMResearchIT/MANSAFT#1]
In the `minpack` directory, running `$ make clean; make FC='nagfor -C=all -u -C=undefined -g -gline -mtrace=on,line,paranoia -Warn=allocation -Warn=subnormal -ieee=stop'`

gives
```
Runtime Error: Ion.f90, line 247: Reference to undefined variable X_SOLV
Program terminated by fatal error
Ion.f90, line 247: Error occurred in ION:A_BORN_DV
Pressure.f90, line 42: Called by PRESSURE:PRESS
Vol.f90, line 74: Called by VOL:VOL_DENS_G
mansaft.f90, line 29: Called by PHA1
```

I'm not in a position to determine the correct fix for this.

**Comment by gcapes** [comment]
If [ion_switch](https://github.com/UoMResearchIT/MANSAFT/blob/master/minpack/Ion.f90#L217) is false, then `x_solv` doesn't get a value assigned to it, hence the error.
Whether I can just move up the [two assignments](https://github.com/UoMResearchIT/MANSAFT/blob/master/minpack/Ion.f90#L229) to before the conditional, I would like confirmed by someone who understands what the code better than me.

**Comment by Yichun886** [comment]
> If [ion_switch](https://github.com/UoMResearchIT/MANSAFT/blob/master/minpack/Ion.f90#L217) is false, then `x_solv` doesn't get a value assigned to it, hence the error.
> Whether I can just move up the [two assignments](https://github.com/UoMResearchIT/MANSAFT/blob/master/minpack/Ion.f90#L229) to before the conditional, I would like confirmed by someone who understands what the code better than me.

 I think you are right. I compared  [Line 229](https://github.com/UoMResearchIT/MANSAFT/blob/master/minpack/Ion.f90#L229) with [Line 155](https://github.com/UoMResearchIT/MANSAFT/blob/master/minpack/Ion.f90#L155), and it makes sense.

**Comment by gcapes** [comment]
Great, thanks!
