### ISSUE TITLE
Undefined variable LP1 in Vol_dens_g

### ISSUE THREAD

**Issue by gcapes** [UoMResearchIT/MANSAFT#2]
```
Runtime Error: Vol.f90, line 79: Reference to undefined variable LP1
Program terminated by fatal error
Vol.f90, line 79: Error occurred in VOL:VOL_DENS_G
mansaft.f90, line 29: Called by PHA1
```
First usage is [here](https://github.com/UoMResearchIT/MANSAFT/blob/master/minpack/Vol.f90#L79) but the assignment is [later on](https://github.com/UoMResearchIT/MANSAFT/blob/master/minpack/Vol.f90#L136)

**Comment by gcapes** [comment]
@Yichun886

**Comment by Yichun886** [comment]
I try to print lv1, lv2, lp1, and lp2 out before [Line 39](https://github.com/UoMResearchIT/MANSAFT/blob/master/minpack/Vol.f90#L39). There are very small numbers. I think the writer forgot to set initial values. Maybe we can try to set them as 0 at the beginning.
